# Generated by Django 5.2.1 on 2025-05-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_apellidos_alter_persona_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.CharField(max_length=3),
        ),
    ]
